/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreatePaperRouteImport } from './routes/create-paper'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PapersIndexRouteImport } from './routes/papers.index'
import { Route as PapersPaperIdRouteImport } from './routes/papers.$paperId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePaperRoute = CreatePaperRouteImport.update({
  id: '/create-paper',
  path: '/create-paper',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersIndexRoute = PapersIndexRouteImport.update({
  id: '/papers/',
  path: '/papers/',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersPaperIdRoute = PapersPaperIdRouteImport.update({
  id: '/papers/$paperId',
  path: '/papers/$paperId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-paper': typeof CreatePaperRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
  '/papers/': typeof PapersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-paper': typeof CreatePaperRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
  '/papers': typeof PapersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-paper': typeof CreatePaperRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
  '/papers/': typeof PapersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-paper'
    | '/dashboard'
    | '/login'
    | '/papers/$paperId'
    | '/papers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-paper'
    | '/dashboard'
    | '/login'
    | '/papers/$paperId'
    | '/papers'
  id:
    | '__root__'
    | '/'
    | '/create-paper'
    | '/dashboard'
    | '/login'
    | '/papers/$paperId'
    | '/papers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatePaperRoute: typeof CreatePaperRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PapersPaperIdRoute: typeof PapersPaperIdRoute
  PapersIndexRoute: typeof PapersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-paper': {
      id: '/create-paper'
      path: '/create-paper'
      fullPath: '/create-paper'
      preLoaderRoute: typeof CreatePaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/': {
      id: '/papers/'
      path: '/papers'
      fullPath: '/papers/'
      preLoaderRoute: typeof PapersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$paperId': {
      id: '/papers/$paperId'
      path: '/papers/$paperId'
      fullPath: '/papers/$paperId'
      preLoaderRoute: typeof PapersPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatePaperRoute: CreatePaperRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PapersPaperIdRoute: PapersPaperIdRoute,
  PapersIndexRoute: PapersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
